version: '2'
services:
  web:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'gitlab'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        gitlab_rails['ldap_enabled'] = true
        gitlab_rails['ldap_host'] = '10.11.1.2'
        gitlab_rails['ldap_port'] = 389
        gitlab_rails['ldap_uid'] = 'uid'
        gitlab_rails['ldap_method'] = 'plain'
        gitlab_rails['ldap_bind_dn'] = 'cn=admin,dc=example,dc=org'
        gitlab_rails['ldap_password'] = 'admin'
        gitlab_rails['ldap_allow_username_or_email_login'] = true
        gitlab_rails['ldap_base'] = 'dc=example,dc=org' 
    ports:
      - '8180:80'
    networks:
      default:
         ipv4_address: 10.11.1.4
networks:
 default:
        external:
            name: TDTest
