version: '3'
services:
  ldap_service:
    image: osixia/openldap:latest
    ports:
      - 389:389
      - 636:636
    hostname: ldap_service
    networks:
      default:
        ipv4_address: 10.11.1.2
  phpldapadmin-service:
    image: osixia/phpldapadmin
    hostname: phpldapadmin-service
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: ldap-host
      PHPLDAPADMIN_HTTPS: 'false'
    ports:
      - 8080:80
    depends_on:
      - ldap_service
    links:
      - ldap_service:ldap-host
    networks:
      default:
         ipv4_address: 10.11.1.3
networks:
 default:
        external:
            name: TDTest
